### ISSUE TITLE
Something is wrong with rohan

### ISSUE THREAD

**Issue by kevinsawicki** [botriot/faceup#3]
Notice the weird artifacts around Obama's face.

This used to rohan properly but is no longer.

![](http://faceup.me/img?src=http://i.imgur.com/qyrr5.jpg&overlay=rohan#.png)

**Comment by wadey** [comment]
I think I know the bug here. I need to convert the coordinates from floats to ints before passing to ImageMagick. It freaks out otherwise.

**Comment by wadey** [comment]
I also changed the version of ImageMagick, so I may need to revert back if that is the problem.

**Comment by jonrohan** [comment]
this looks fixed?
